### ISSUE TITLE
Error while trading

### ISSUE THREAD

**Issue by litasio** [DexKit/trading-bot#1]
All allowances ok we are ready for trade
[AxiosError: Request failed with status code 400] {

**Comment by JoaoCampos89** [comment]
Can you share your config here? Without the tokens that you are trading and I am not able to find out which issue it is

**Comment by kumarbitindi** [comment]
hi i am trying it on BSC network and using https://api.owlracle.info/v3/bsc/gas this for gas 



import { ChainId } from "@0x/contract-addresses";
import axios from "axios";
import { ethers } from "ethers";






export const getGasEstimation = async (chainId: ChainId) => {

    if (chainId === ChainId.BSC) {
        const gasEstimation = await (await axios.get('https://api.owlracle.info/v3/bsc/gas')).data['speeds'];
        // solution presented at https://github.com/ethers-io/ethers.js/issues/2828
        const maxFeePerGas = ethers.utils.parseUnits(
            Math.ceil(gasEstimation.maxFee) + '',
            'gwei'
        )
        const maxPriorityFeePerGas = ethers.utils.parseUnits(
            Math.ceil(gasEstimation.maxPriorityFee) + '',
            'gwei'
        )
        return { maxFeePerGas, maxPriorityFeePerGas }
    }

    return {}

}

**Comment by kumarbitindi** [comment]
data: { code: 111, reason: 'Gas estimation failed' }  its keep failing
